version: '3.3'    
services:
  poll-bme280:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - /app/poll-bme280.py
    restart: always
    depends_on:
      - influxdb
  poll-octopus:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - poll-octopus.py
    restart: always
    depends_on:
      - influxdb
  poll-internet:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - poll-internet.py
    restart: always
    depends_on:
      - influxdb
  patch-cloudflare:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    command:
      - patch-cloudflare.py
    restart: always
    depends_on:
      - influxdb
  flask-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./secret.py:/app/secret.py
    environment:
      - FLASK_APP=./flask-server.py
    entrypoint:
      - flask
    command:
      - run
      - --host=0.0.0.0
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana:8.1.5
    restart: always
    volumes:
      - ./etc/grafana/:/etc/grafana
      - ./var/lib/grafana:/var/lib/grafana
    depends_on:
      - influxdb
  influxdb:
     image: arm64v8/influxdb:1.7
     ports:
       - "8086:8086"
     volumes:
       - ../influxdb:/var/lib/influxdb
       - ./etc/influxdb:/etc/influxdb
     restart: always
  nginx:
    image: nginx:1.21-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    restart: always
  certbot:
    image: certbot/certbot:arm64v8-v1.19.0
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - nginx
